server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/blog"
    username: "username"
    password: "password"
  application:
    name: blog
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  signerKey: "7xGpvSnXBCjwOGJ7QtQyUpXgpqjOoqYmYUoVLHyY6AVi8Q079tH3LQSUn8zwDnWGx0DX7vhD"